name: Python checks
on:
  pull_request:
    types: [assigned]
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      placeholder:
        description: "placeholder, no effect"
        required: false
jobs:
  check_license_and_format:
    name: License and format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Check Python format
        id: py_check
        run: |
          python3 -m pip install black==19.10b0
          python3 ci/check/run_py_format.py --source_dir $PWD
      - name: Run Python Format
        id: py_fmt
        run: |
          python3 -m pip install black==19.10b0
          python3 ci/check/run_py_format.py --source_dir $PWD --fix
      - name: install clang-format
        id: clang-format
        run: sudo apt install clang-format
      - name: Run clang-format
        id: C_fmt
        run: find . -regex '.*\.\(cpp\|hpp\|cu\|c\|h\)' -exec clang-format -style=file -i {} \;
      - name: check for changes
        run: |
          if git diff --exit-code; then
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "has_changes=true" >> $GITHUB_ENV
          fi
      - name: Git push
        if: ${{ env.has_changes == 'true' }}
        id: git_push
        run: |
          git config --global user.email "derrylin@hust.edu.cn"
          git config --global user.name "ci-bot"
          git add -u
          git commit -m "auto format by CI"
          git push
